server.port=5050

server.servlet.session.timeout=5m

spring.application.name=home

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.properties.hibernate.type.preferred_instant_jdbc_type=TIMESTAMP
spring.jpa.open-in-view=false

chrome.executable-path=${CHROME_EXECUTABLE_PATH:C:/Program Files/Google/Chrome/Application/chrome.exe}
chrome.user-data-directory=${CHROME_USER_DATA_DIRECTORY:C:/ChromeProfile}
chrome.remote-debugging-port=${CHROME_REMOTE_DEBUGGING_PORT:9222}
chrome.arguments=${CHROME_ARGUMENTS:}
chrome.desktop-url=${CHROME_DESKTOP_URL:}

tcg.deck.resource-pattern=${TCG_DECK_RESOURCE_PATTERN:classpath*:tcg/deck/*.csv}
tcg.cardmarket.browser-endpoint=${TCG_CARDMARKET_BROWSER_ENDPOINT:http://localhost:${chrome.remote-debugging-port}}

event.processing-timeout=1h
event.stuck.scheduler.delay=1m

frontend.scheduler.notification.delay=1s
frontend.sse.heartbeat.delay=15s

tcg.cardmarket.request-delay-min=2s
tcg.cardmarket.request-delay-max=5s
tcg.scheduler.refresh-prices.delay=10s
tcg.scheduler.save-decks.delay=10s
