server.port=5050

server.servlet.session.timeout=5m

spring.application.name=home

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.properties.hibernate.type.preferred_instant_jdbc_type=TIMESTAMP

tcg.cardmarket.request-delay-min=2s
tcg.cardmarket.request-delay-max=5s
tcg.scheduler.refresh-prices.delay=10s
tcg.scheduler.save-decks.delay=10s

frontend.scheduler.notification.delay=1s

event.processing-timeout=1h
event.stuck.scheduler.delay=1m
