spring.application.name=home

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.properties.hibernate.type.preferred_instant_jdbc_type=TIMESTAMP