CREATE TABLE CARDMARKET_CARD (
  	ID VARCHAR2(255) PRIMARY KEY,
  	LINK VARCHAR2(255) NOT NULL
);

CREATE TABLE CARDMARKET_DECK (
    ID VARCHAR2(255) PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL
);

CREATE TABLE CARDMARKET_DECK_CARD (
    ID VARCHAR2(255) PRIMARY KEY,
    DECK_ID VARCHAR2(255) NOT NULL,
    CARD_ID VARCHAR2(255) NOT NULL,
    QUANTITY NUMBER(10) NOT NULL,

    CONSTRAINT UQ_DECK_CARD UNIQUE (DECK_ID, CARD_ID),

    CONSTRAINT FK_DECK_CARD_DECK
        FOREIGN KEY (DECK_ID) REFERENCES CARDMARKET_DECK(ID),

    CONSTRAINT FK_DECK_CARD_CARD
        FOREIGN KEY (CARD_ID) REFERENCES CARDMARKET_CARD(ID),

    CONSTRAINT CK_DECK_CARD_QUANTITY
        CHECK (QUANTITY > 0)
);