CREATE TABLE CARDMARKET_CARD (
    ID VARCHAR2(255) PRIMARY KEY,
    LINK VARCHAR2(255) NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL,
    LAST_MODIFIED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL
);

CREATE TABLE CARDMARKET_DECK (
    ID VARCHAR2(255) PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    DELETED_AT TIMESTAMP(6),
    CURRENT_VERSION_ID VARCHAR2(255),
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL,
    LAST_MODIFIED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL,

    CONSTRAINT CK_DECK_STATUS CHECK (STATUS IN ('ACTIVE', 'ARCHIVED', 'DELETED'))
);

CREATE TABLE CARDMARKET_DECK_VERSION (
    ID VARCHAR2(255) PRIMARY KEY,
    DECK_ID VARCHAR2(255) NOT NULL,
    VERSION_NUMBER NUMBER(10) NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL,
    LAST_MODIFIED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL,

    CONSTRAINT UQ_DECK_VERSION UNIQUE (DECK_ID, VERSION_NUMBER),
    CONSTRAINT FK_DECK_VERSION_DECK
        FOREIGN KEY (DECK_ID) REFERENCES CARDMARKET_DECK(ID)
);

CREATE TABLE CARDMARKET_DECK_VERSION_CARD (
    ID VARCHAR2(255) PRIMARY KEY,
    DECK_VERSION_ID VARCHAR2(255) NOT NULL,
    CARD_ID VARCHAR2(255) NOT NULL,
    QUANTITY NUMBER(10) NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL,
    LAST_MODIFIED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL,

    CONSTRAINT UQ_DECK_VERSION_CARD UNIQUE (DECK_VERSION_ID, CARD_ID),
    CONSTRAINT FK_DECK_VERSION_CARD_VERSION
        FOREIGN KEY (DECK_VERSION_ID) REFERENCES CARDMARKET_DECK_VERSION(ID),
    CONSTRAINT FK_DECK_VERSION_CARD_CARD
        FOREIGN KEY (CARD_ID) REFERENCES CARDMARKET_CARD(ID),
    CONSTRAINT CK_DECK_VERSION_CARD_QUANTITY CHECK (QUANTITY > 0)
);

ALTER TABLE CARDMARKET_DECK ADD CONSTRAINT FK_DECK_CURRENT_VERSION
    FOREIGN KEY (CURRENT_VERSION_ID) REFERENCES CARDMARKET_DECK_VERSION(ID);
