CREATE TABLE APP_USER (
    ID VARCHAR2(255) PRIMARY KEY,
    USERNAME VARCHAR2(255) NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL,
    LAST_MODIFIED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL,

    CONSTRAINT UQ_APP_USER_USERNAME UNIQUE (USERNAME)
);

CREATE TABLE APP_USER_ROLE (
    USER_ID VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(32) NOT NULL,

    CONSTRAINT PK_APP_USER_ROLE PRIMARY KEY (USER_ID, ROLE),
    CONSTRAINT FK_APP_USER_ROLE_USER
        FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID) ON DELETE CASCADE
);
