CREATE TABLE APPLICATION_EVENT (
    ID VARCHAR2(255) PRIMARY KEY,
    TYPE VARCHAR2(64) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'TO_DO' NOT NULL,
    PROCESSED_AT TIMESTAMP(6),
    MESSAGE VARCHAR2(4000),
    ERROR_MESSAGE VARCHAR2(4000),
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL,
    LAST_MODIFIED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL
);

CREATE INDEX IX_APPLICATION_EVENT_STATUS
    ON APPLICATION_EVENT (TYPE, STATUS, CREATED_AT);
