CREATE TABLE APPLICATION_EVENT (
    ID VARCHAR2(255) PRIMARY KEY,
    TYPE VARCHAR2(64) NOT NULL,
    PROCESSED_AT TIMESTAMP(6),
    ERROR_MESSAGE VARCHAR2(4000),
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL,
    LAST_MODIFIED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL,

    CONSTRAINT CK_APPLICATION_EVENT_TYPE CHECK (
        TYPE IN ('SAVE_DECKS_FROM_RESOURCE', 'REFRESH_DECK_PRICES')
    )
);

CREATE INDEX IX_APPLICATION_EVENT_PENDING
    ON APPLICATION_EVENT (TYPE, PROCESSED_AT, CREATED_AT);
