CREATE TABLE APPLICATION_LOG (
    ID VARCHAR2(255) PRIMARY KEY,
    METHOD_NAME VARCHAR2(1000) NOT NULL,
    METHOD_INPUT CLOB,
    METHOD_OUTPUT CLOB,
    ERROR CLOB,
    DURATION_MS NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_MODIFIED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL,
    LAST_MODIFIED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL
);

CREATE INDEX IX_APPLICATION_LOG_METHOD_CREATED_AT
    ON APPLICATION_LOG (METHOD_NAME, CREATED_AT);
