CREATE TABLE MEDIA_ACTOR (
    ID VARCHAR2(255) PRIMARY KEY,
    NAME VARCHAR2(255 CHAR) NOT NULL,
    STATUS VARCHAR2(8) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL,
    LAST_MODIFIED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL,
    CONSTRAINT UQ_MEDIA_ACTOR_NAME UNIQUE (NAME),
    CONSTRAINT CK_MEDIA_ACTOR_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);
CREATE TABLE MEDIA_FOLDER (
    ID VARCHAR2(255) PRIMARY KEY,
    PATH VARCHAR2(1000 CHAR) NOT NULL,
    TYPE VARCHAR2(255 CHAR) NOT NULL,
    STATUS VARCHAR2(8) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL,
    LAST_MODIFIED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL,
    CONSTRAINT UQ_MEDIA_FOLDER_PATH UNIQUE (PATH),
    CONSTRAINT CK_MEDIA_FOLDER_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);
CREATE TABLE MEDIA_VIDEO (
    ID VARCHAR2(255) PRIMARY KEY,
    NAME VARCHAR2(255 CHAR) NOT NULL,
    FOLDER_ID VARCHAR2(255) NOT NULL,
    ACTOR_KEY VARCHAR2(64) NOT NULL,
    FILE_NAME VARCHAR2(1000 CHAR) NOT NULL,
    STATUS VARCHAR2(8) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL,
    LAST_MODIFIED_BY VARCHAR2(255) DEFAULT 'system' NOT NULL,
    CONSTRAINT FK_MEDIA_VIDEO_FOLDER FOREIGN KEY (FOLDER_ID) REFERENCES MEDIA_FOLDER(ID),
    CONSTRAINT UQ_MEDIA_VIDEO_IDENTITY UNIQUE (FOLDER_ID, NAME, ACTOR_KEY),
    CONSTRAINT CK_MEDIA_VIDEO_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);
CREATE TABLE MEDIA_VIDEO_ACTOR (
    VIDEO_ID VARCHAR2(255) NOT NULL,
    ACTOR_ID VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_MEDIA_VIDEO_ACTOR PRIMARY KEY (VIDEO_ID, ACTOR_ID),
    CONSTRAINT FK_MEDIA_VA_VIDEO FOREIGN KEY (VIDEO_ID) REFERENCES MEDIA_VIDEO(ID),
    CONSTRAINT FK_MEDIA_VA_ACTOR FOREIGN KEY (ACTOR_ID) REFERENCES MEDIA_ACTOR(ID)
);
CREATE INDEX IX_MEDIA_VA_ACTOR ON MEDIA_VIDEO_ACTOR (ACTOR_ID);
CREATE INDEX IX_MEDIA_ACTOR_STATUS ON MEDIA_ACTOR (STATUS);
CREATE INDEX IX_MEDIA_FOLDER_STATUS ON MEDIA_FOLDER (STATUS);
CREATE INDEX IX_MEDIA_VIDEO_STATUS ON MEDIA_VIDEO (STATUS);

